webtalk_init -webtalk_dir D:/MYHUST/sophomore_year/second_semester/CCIT/MIPS_Micro_Processer/MIPS_Micro_Processer.sim/sim_1/behav/xsim/xsim.dir/Controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 29 15:38:48 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b1955bd8-c9e9-471c-9377-34fa97681e92" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b18f18cf72349f0946ab7b3325de529" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "45 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1594797148 -regid "" -xml D:/MYHUST/sophomore_year/second_semester/CCIT/MIPS_Micro_Processer/MIPS_Micro_Processer.sim/sim_1/behav/xsim/xsim.dir/Controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MYHUST/sophomore_year/second_semester/CCIT/MIPS_Micro_Processer/MIPS_Micro_Processer.sim/sim_1/behav/xsim/xsim.dir/Controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MYHUST/sophomore_year/second_semester/CCIT/MIPS_Micro_Processer/MIPS_Micro_Processer.sim/sim_1/behav/xsim/xsim.dir/Controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
